services:
  #Django appserver
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - django_redis
      - django_db

  #Django Redis
  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - 6379:6379

  #Database
  django_db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql

  #Celery sever worker
  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app
    ports:
      - 8001:8001
    depends_on:
      - django_redis
      - django_db
